### ISSUE TITLE
Search on conversation list when there's a custom categories text as last message.

### ISSUE THREAD

**Issue by james8885** [cometchat-pro/android-java-chat-ui-kit#1]
### Describe the problem

When there's a last message (custom categories message) in the conversation list and user did a search. The application crash.

### What was the expected behavior?

It will be able to filter without crashing.

### Reproduction

Step 1: Send a custom categories message.
Step 2: Open the app and do a search on the conversation list.
After this the program crashes.

### Environment

Productions

- **Version used:V2.0.1**
- **Other modules/plugins/libraries that might be involved: N/A**

**Comment by darshanbhanushali** [comment]
Hi @james8885 ,

Please check our latest UI Kit v2.0.2, we have fixed this issue by adding a check for TEXT_MESSAGE Type in Filterable method of ConversationAdapter class.
