### ISSUE TITLE
Chat : Voice Note not working in Android 11 and above versions

### ISSUE THREAD

**Issue by Nivs113** [cometchat-pro/android-java-chat-ui-kit#7]
After Record Voice Note, Display "No File Found! Please" message displayed and when click on Send button nothing to be send. I have attached screenshot of error log in below, please look in to it and resolve. 
Thank you in advance.

![image](https://user-images.githubusercontent.com/26837785/156870266-d958b51f-fb18-42bf-91b6-1053620fe507.png)

![image](https://user-images.githubusercontent.com/26837785/156870460-fdafd03c-a51b-4c81-88d4-e2e515fc76de.png)

**Comment by darshanbhanushali** [comment]
Hello,

Can you please check code snippet shown in below link and replace `getOutputMediaFile(Context context)` under `Utils.java` file. We have added an certain check to support Audio Files for Android 11.
https://github.com/cometchat-pro/android-java-chat-ui-kit/blob/pluto/CometChatWorkspace/src/main/java/com/cometchatworkspace/resources/utils/Utils.java#L675-L695

**Comment by rahulalanmitra** [comment]
Hi there,
Hope you are doing well.

I hope the information shared by Darshan was helpful to you. If not, it would be great if we could connect to discuss this further. You can write to us at [help@cometchat.com](help@cometchat.com) or reach out to us through [Intercom](https://www.cometchat.com/contact-support). We'll be happy to examine this further.

Regards,
Rahul
