### ISSUE TITLE
java.lang.IllegalArgumentException: com.immigration_app: Targeting S+ (version 31 and above)

### ISSUE THREAD

**Issue by mukeshocpc** [cometchat-pro/android-java-chat-ui-kit#9]
Getting an error once a call is received in android.
<img width="1423" alt="Screenshot 2022-06-09 at 9 21 01 PM" src="https://user-images.githubusercontent.com/30304398/172897429-d3edeba5-d063-4fde-a01d-008f074344cf.png">

**Comment by darshanbhanushali** [comment]
Hello, 

We have fixed this issue and released our UI Kit. We suggest you please check the below link to know the changes and do the same in your `OngoingService.java `file.

https://github.com/cometchat-pro/android-java-chat-ui-kit/blob/master/uikit/src/main/java/com/cometchat/pro/uikit/ui_components/calls/call_manager/ongoing_call/OngoingCallService.java#L52

**Comment by mukeshocpc** [comment]
Hi i have done the push notification setup getting success as well so as of now FCM key is added in comet portal and token is updated  but still i am not getting push notification .
<img width="918" alt="Screenshot 2022-06-15 at 9 43 02 PM" src="https://user-images.githubusercontent.com/30304398/173875383-7fc9d18f-6e20-4d0f-8d0e-c4957509edfb.png">

**Comment by darshanbhanushali** [comment]
Hello,

Can you please check the other steps like integrating Firebase into your app? To handle Push Notifications you need to create a FirebaseService which includes `onMessageReceived(RemoteMessage message)` method. This method gets triggered whenever a device receives any push notification. We suggest you to please check our [MyFirebaseMessagingService](https://github.com/cometchat-pro/android-java-chat-push-notification-app/blob/master/Firebase/app/src/main/java/com/cometchat/pro/android/pushnotification/utils/MyFirebaseMessagingService.java) file from our sample app for reference.

Also please check below documentation link to learn more about Push Notification Setup in Android App.
https://www.cometchat.com/docs/extensions/android-push-notifications#android-app-setup
